server:
  port: 1001

logging:
  level:
    com.dw.wechatmessage: debug

# 微信测试号配置
wechat:
  appId: wxf2a8e0bbcc0e5fbb
  secret: 31f6b91e51633b534c41ee3c28d319fb
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s

bus:
  interface:
    url: https://api.shmaas.net/traffic/v1/getbusstoparrivedetails
    cityCode: 310100
  query:
    work:
      - lineId: 1256
        lineName: 莲亭专线
        stopId: 21
        metroType: 0
        language: zh-cn
        stopName: 新车公路书林路
        direction: 1
      - lineId: 1002
        lineName: 莲金专线
        stopId: 37
        metroType: 0
        language: zh-cn
        stopName: 车新公路书林路(招呼站)
        direction: 1
      - lineId: 510700
        lineName: 上石线
        stopId: 55
        metroType: 0
        language: zh-cn
        stopName: 新车公路书林路
        direction: 0